---
- hosts: pg_dev_single
  become: True
  vars_files:
    - vars/main.yaml

  pre_tasks:
    - name: "Inclde OS specific vars"
      include_vars: "vars/{{ ansible_os_family }}.yaml"

    - name: "Print OS family"
      debug:
        msg:
          - "{{ ansible_os_family }}"
          - "{{ ansible_os_family ~ '-' ~ ansible_distribution_major_version }}"

  roles:
    - firewall
    - selinux
    - sysctl
    - pgdg_repo
    - postgres_packages
    - postgres_limits
    - postgres_config
