---
- hosts: pg_dev_single
  become: True
  vars_files:
    - vars/main.yaml

  roles:
    - firewall
    - selinux
    - sysctl
    - pgdg_repo
    - postgres_packages
    - postgres_limits
    - postgres_config
