---
    - name: "Install PostgreSQL Packages"
      yum:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
        disable_gpg_check: yes
        update_cache: no
      loop: "{{ postgres_packages | list }}"