---
- block:
    - name: PostgreSQL | check if appstream module is enabled
      command: 'dnf -y -C module list postgresql'
      register: postgresql_module_result
      changed_when: false
      args:
        warn: false

    - name: PostgreSQL | disable appstream module
      command: 'dnf -y -C module disable postgresql'
      args:
        warn: false
      when: "'[x] ' not in postgresql_module_result.stdout"
  when: installation_method == "repo" and
        ansible_os_family == "RedHat" and
        ansible_distribution_major_version >= '8'
  ignore_errors: true
  tags: install_postgres

- name: "Install PostgreSQL Packages"
  yum:
    name: "{{ item }}"
    state: "present"
    disable_gpg_check: yes
    update_cache: no
  loop: "{{ common_pg_packages | list }}"