---
    - name: Add IP hostname into /etc/hosts file
      lineinfile:
        path: /etc/hosts
        regexp: "{{ etc_hosts_regexp }}"
        line: "{{ etc_hosts_entry }}"
        state: present
        insertbefore: EOF