---
    - name: "Set {{ pg_user }} OS user limits"
      pam_limits:
        domain: "{{ item.domain }}"
        limit_type: "{{ item.type }}"
        limit_item: "{{ item.item }}"
        value: "{{ item.value }}"
      loop: "{{ postgres_user_limits | list | unique }}"